n=input('Digite algo:')
print('O tipo primitivo desse valor é: ', type(n))
print('Só tem espaço?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúsculo?', n.isupper())
print('Está em minúscula?', n.islower())
print('Está capitalizada? ', n.istitle())
